system:
  syslog:
    file:
    - contents:
      - notice: true
        name: any
      name: messages
  extensions:
    providers:
    - license_type:
      - deployment_scope: commercial
        name: juniper
      name: juniper
    - license_type:
      - deployment_scope: commercial
        name: juniper
      name: chef
routing_options:
  forwarding_table:
    ecmp_fast_reroute: true
    export: PFE-LB
version: 18.1R3-S5.3
interfaces:
  interface:
  - unit:
    - name: '0'
    name: xe-0/0/0
    description: '*** to dc1-borderleaf1 ***'
  - unit:
    - name: '0'
    name: xe-0/0/1
    description: '*** to dc1-borderleaf2 ***'
  - unit:
    - name: '0'
    name: xe-0/0/2
    description: '*** to dc1-leaf1 ***'
  - unit:
    - name: '0'
    name: xe-0/0/3
    description: '*** to dc1-leaf2 ***'
  - unit:
    - name: '0'
    name: xe-0/0/4
    description: '*** to dc1-leaf3 ***'
  - unit:
    - name: '0'
      description: '*** management ***'
    name: em0
  - unit:
    - description: '*** to pfe ***'
      family:
        inet:
          address:
          - name: 169.254.0.2/24
      name: '0'
    name: em1
  - unit:
    - name: '0'
      description: '*** loopback ***'
    name: lo0
policy_options:
  policy_statement:
  - name: IPCLOS_BGP_EXP
    term:
    - from:
        protocol: bgp
      then:
        accept: true
        community:
        - add: true
      name: loopback
    - then:
        reject: true
      name: default
  - name: IPCLOS_BGP_IMP
    term:
    - from:
        protocol: direct
      name: loopback
      then:
        accept: true
    - name: default
      then:
        reject: true
  - then:
      load_balance:
        per_packet: true
    name: PFE-LB
forwarding_options:
  storm_control_profiles:
  - all: ''
    name: default
protocols:
  bgp:
    group:
    - allow: 10.30.100.0/24
      multipath: ''
      name: EVPN_iBGP
      type: internal
      family:
        evpn:
          signaling: ''
      local_as:
        as_number: '65200'
    - multipath:
        multiple_as: true
      vpn_apply_export: true
      mtu_discovery: true
      name: IPCLOS_eBGP
      export: IPCLOS_BGP_EXP
      bfd_liveness_detection:
        multiplier: '3'
        minimum_interval: '1000'
      type: external
      import: IPCLOS_BGP_IMP
  igmp_snooping:
    vlan:
    - name: default
_merge_directive: merge_recursive
