security:
  policies:
    policy:
    - from_zone_name: trust
      to_zone_name: untrust
      policy:
      - name: default-permit
        match:
          source_address: any
          destination_address: any
          application: any
        then:
          permit: ''
  _merge_directive: merge_recursive
_merge_directive: merge_recursive
