interfaces:
  interface:
  - unit:
    - family:
        inet: {}
      name: '1'
    - family:
        inet: {}
      name: '2'
    - family:
        inet: {}
      name: '3'
    name: ge-0/0/0
  - unit:
    - family:
        inet: {}
      name: '1'
    - family:
        inet: {}
      name: '2'
    - family:
        inet: {}
      name: '3'
    name: ge-0/0/1
  - unit:
    - family:
        inet: {}
      name: '0'
    name: fxp0