system:
  services:
    netconf:
      ssh: ''
  _merge_directive: merge_recursive
snmp:
  community:
  - name: public
    authorization: read-only
policy_options: {}
routing_options:
  static:
    route:
    - name: 0.0.0.0/0
      next_hop: 100.123.0.1
_merge_directive: merge_recursive
