interfaces:
  interface:
  - name: ae0
    esi: {}
    unit:
    - family:
        ethernet_switching:
          vlan: {}
      name: '0'
    aggregated_ether_options:
      lacp: {}
  - unit:
    - family:
        inet: {}
      name: '10001'
    - family:
        inet: {}
      name: '10002'
    - family:
        inet: {}
      name: '10003'
    name: lo0
switch_options:
  _merge_directive: merge_recursive
  route_distinguisher:
    _merge_directive: merge_recursive
routing_instances:
  _merge_directive: merge_recursive
  _merge_list_directives:
    instance:
      _merge_directive: merge_by_key
      _merge_key: name
  instance:
  - route_distinguisher: {}
    name: VRF_10001
  - route_distinguisher: {}
    name: VRF_10002
  - route_distinguisher: {}
    name: VRF_10003